### ISSUE TITLE
installing Chrome ext - getmystuff

### ISSUE THREAD

**Issue by momlaberee** [eloquence/freeyourstuff.cc#101]
I have tried many times to install this extension (getmystuff) but I just get a dead response - nothing happens at all.  I need a hand troubleshooting this!  Thank you,
Ro L.

**Comment by eloquence** [comment]
Hm, looks like the installation via https://freeyourstuff.cc/ is currently broken, will investigate. Try installing directly from the extension store: https://chrome.google.com/webstore/detail/free-your-stuff/hlkhpekhgcaigleojiocoeockhcaglia?hl=en

**Comment by eloquence** [comment]
Installation via website should be fixed now; let me know if you still encounter this problem. Closing for now.
