### ISSUE TITLE
Quora plugin no longer appears to download question title?

### ISSUE THREAD

**Issue by vttoth** [eloquence/freeyourstuff.cc#102]
I see that this has been an issue before but it appears to have popped up again: The Quora plugin no longer seems to download question titles. URLs and answer texts download just fine.

**Comment by eloquence** [comment]
Thanks as always for the report! This was due to a CSS change on Quora's side; it should be resolved in the latest version (may take a few hours to update automatically, once it shows "0.4.8" in your extensions list you're up to date). Please let me know if you still encounter it after the update.

**Comment by vttoth** [comment]
Thank you. Sorry for not responding sooner, never got the e-mail from GitHub. The plugin works fine now. I have yet to try if it can grab my 6000+ answers crash-free (I have not had much luck with that before) but I was able to manually interrupt the download with the debugger and just copy-paste my later answers into an earlier JSON.
