### ISSUE TITLE
“Please log into Quora first.” 

### ISSUE THREAD

**Issue by michaelzed** [eloquence/freeyourstuff.cc#138]
Hitting the "Retrieve my Contributions" button gives a red message below “Please log into Quora first.” I am logged in. Tried to uninstall then reinstall the extension, but same result.

Using freeyourstuff 0.6.1, Chrome 81.0.4044.138/Mac.

**Comment by eloquence** [comment]
Unfortunately this is a known issue with the Quora plugin. Quora redesigned its feed under the hood a while ago, making it very difficult to parse reliably. I'll take one final stab at trying to get it to work again this weekend, and if that doesn't do it, I'll have to disable Quora support for now. :(

**Comment by eloquence** [comment]
(See #137 for latest update, closing as duplicate)
