### ISSUE TITLE
Does not work with Quora

### ISSUE THREAD

**Issue by phillipremaker** [eloquence/freeyourstuff.cc#139]
When running FreeYourStuff on Quora, I get the error "Please log into Quora first." even though I am already logged in. Permissions have been granted.

**Comment by eloquence** [comment]
Unfortunately this is a known issue with the Quora plugin. Quora redesigned its feed under the hood a while ago, making it very difficult to parse reliably. I'll take one final stab at trying to get it to work again this weekend, and if that doesn't do it, I'll have to disable Quora support for now. :(

**Comment by eloquence** [comment]
(See #137 for latest update, closing as duplicate)
