### ISSUE TITLE
Will not download even though signed into Quora.

### ISSUE THREAD

**Issue by mainemoose77** [eloquence/freeyourstuff.cc#140]
![image](https://user-images.githubusercontent.com/10585751/90407356-6dbaac80-e074-11ea-9b5d-e7fb71dc6a64.png)

**Comment by eloquence** [comment]
Unfortunately this is a known issue with the Quora plugin. Quora designed its feed under the hood a while ago, making it very difficult to parse reliably. I'll take one final stab at trying to get it to work again this weekend, and if that doesn't do it, I'll have to disable Quora support for now. :(

**Comment by eloquence** [comment]
(See #137 for latest update, closing as duplicate)
