### ISSUE TITLE
Keeps asking me to login to Yelp

### ISSUE THREAD

**Issue by cultdoctor** [eloquence/freeyourstuff.cc#144]
I'm logged in, but keeps telling me to do so
![Screenshot 2020-10-11 at 20 04 38](https://user-images.githubusercontent.com/43972014/95695545-0bf26b00-0bfd-11eb-9f9c-cc9abdae1b85.png)

**Comment by eloquence** [comment]
Apologies for the delayed response. This was due to a change in the layout of Yelp's login button; I've updated the extension to match and submitted a new version. Now we're at the mercy of Google's review process, but I'll close the issue once the new version is live.

**Comment by eloquence** [comment]
This should be fixed in the latest released version (0.6.3); if you visit `chrome://extensions` it'll show you the extension version. If you're up-to-date and still see the issue, please let me know :)
