### ISSUE TITLE
Add link to download browser extension to homepage

### ISSUE THREAD

**Issue by philipn** [eloquence/freeyourstuff.cc#16]
When you're logged in, the homepage (or whatever page you see upon login -> redirection) should probably show a big "download browser extension" button.

Right now, clicking on "Download the browser extension" from e.g. https://freeyourstuff.cc/user/twitter/5715a801fa092d382cfdcd83 takes me back to the homepage, which doesn't have a link to the extension.

Before the extension is in the e.g. Chrome app store, I'd suggest linking to https://github.com/eloquence/freeyourstuff.cc#extension-setup.  It threw me through a loop just now :)

**Comment by eloquence** [comment]
*nod* While we're in alpha-testing users have to manually unpack the extension per the instructions -- until we publish to the Chrome store. I'll try to make that clearer.

**Comment by eloquence** [comment]
Tried to make things clearer by not sending folks to GitHub for the docs - better? see https://freeyourstuff.cc/
