### ISSUE TITLE
missing product name/hyperlink in a collection

### ISSUE THREAD

**Issue by brainwane** [eloquence/freeyourstuff.cc#27]
One of the reviews in https://freeyourstuff.cc/view/amazon/5716d1408708521e387a83e7 ("Sheila Shine", I gather from the text of the review) doesn't have the name of the product in the Product column -- it's blank -- and thus there's also no link to the thing being reviewed. Import error?

**Comment by eloquence** [comment]
Thanks for noticing that! Amazon.com sometimes removes product listings, but still keeps the reviews attached to their product ID. So you end up with productless review pages like this:

https://www.amazon.com/gp/review/R3DFFJTX6HZI5T

As far as I can tell, there's no reference to the original product anywhere - let me know if you find anything! Incidentally, a reason to backup one's reviews .. ;-)

**Comment by eloquence** [comment]
Closed for now as issue appears to be on Amazon's end, per above.
