### ISSUE TITLE
Investigate Quora support

### ISSUE THREAD

**Issue by eloquence** [eloquence/freeyourstuff.cc#28]
A couple of folks have requested support for Quora answers, let's see how hard this would be.

**Comment by eloquence** [comment]
Quora answers added :)

**Comment by gcy5s4ti** [comment]
Every time I try to **free my stuff** on Quora it displays the message:

> Waiting for data...

and then fails saying:

> We don't seem to be getting all the answers. Sorry! :-( 

Is there a preferred Chrome version, configuration or known incompatibility?
Thanks.

**Comment by eloquence** [comment]
Hey there --

Since Chrome auto-updates, the extension is mostly tested with the latest
versions (50+). It might be a version issue, or something else. If you
don't mind sharing it, you can send me a link to your Quora profile and I
can investigate if there's something in particular that causes it to choke
up.

Hope that helps,

Erik



2016-06-14 12:26 GMT-07:00 gcy5s4ti <notifications@github.com>:

**Comment by eloquence** [comment]
Oh, I think I see the source of the problem. You have more than 1,000 answers, and Quora adds a little thousands comma separator with such a high number. The code fails to account for that and incorrectly parses the number. Should have a fix ready shortly.

**Comment by eloquence** [comment]
@gcy5s4ti , this should be fixed in the just-released version 0.3.4. You can wait for the auto-update, or uninstall and reinstall the extension from https://freeyourstuff.cc/ . Let me know if that works for you.

FYI, with such a huge number of reviews it's going to take quite a while - but should be fine to keep it running in its tab while doing other things.
