### ISSUE TITLE
Investigate phantomjs for test execution

### ISSUE THREAD

**Issue by eloquence** [eloquence/freeyourstuff.cc#52]
jsdom is pretty flaky - let's see if we can make the tests more sane by moving to phantom.

**Comment by brainwane** [comment]
The maintainer of PhantomJS is [stepping down](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE) so another choice might be better for the long term.

**Comment by eloquence** [comment]
We're migrating the tests to puppeteer shortly, closing
