### ISSUE TITLE
We don't seem to be getting all the answers. Sorry! :-( 

### ISSUE THREAD

**Issue by Deejep** [eloquence/freeyourstuff.cc#61]
That is the message I got when retrieving my Quora content.

**Comment by eloquence** [comment]
Thanks for the report. Quora changed its layout and the plugin is broken right now. I'll look into it.

**Comment by eloquence** [comment]
@Deejep It looks like Quora (temporarily?) changed its layout back to the old design. Can you test if the extension works for you now?

**Comment by Deejep** [comment]
works thx !
