### ISSUE TITLE
Quora Answer Capture Bug #2

### ISSUE THREAD

**Issue by BobRedCo** [eloquence/freeyourstuff.cc#74]
Answers cannot be ordered chronologically. If you click on the up or down arrow for Date, it changes the order in some way but not in strictly date order--the dates skip around all over the place.

**Comment by eloquence** [comment]
I may be overlooking something, but when I look at your [recently uploaded answers](https://freeyourstuff.cc/view/quora/597258f0dca98f5c66fb5254) and click the date arrows, it sorts correctly for me. On first click, it sorts oldest first:

- March 5, 2014
- February 11, 2016
- January 4, 2017
- January 6, 2017
...

On second click, it sorts newest first:

- July 21, 2017 (several answers)
- July 20, 2017
- July 16, 2017
...

Are those not the results you're getting, or am I missing something obvious?

**Comment by BobRedCo** [comment]
Oh, I see! I thought the little arrow to the left of the date was what you
clicked to get ascending date order, but it's actually related to ordering
answers (however that's determined). So if I click on the little arrow to
the right, it works fine.

 

Sorry!

 

  _____

**Comment by eloquence** [comment]
No worries, I can see how it's a bit confusing given how wide the middle column is. Closing for now. Thanks for the reports!
