### ISSUE TITLE
Error with Quora plugin

### ISSUE THREAD

**Issue by TorontoFred** [eloquence/freeyourstuff.cc#81]
Error: Attempt to obtain answer timed out after 30 seconds
    at extractAndStoreAnswer (file:///C:/Users/Fred/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/hlkhpekhgcaigleojiocoeockhcaglia/0.3.22_0/src/plugins/quora/index.js:173:19)
    at

**Comment by TorontoFred** [comment]
less than 500 questions.  And less than 500 collapsed answers.  I didn't know I had that many collapsed answers!!  I'm going to reboot the system and try it again.

**Comment by eloquence** [comment]
Hi! Thanks for the bug report. Could you post the URL to your Quora profile, or email it to me at `eloquence at gmail dot com`? That would enable me to try to reproduce the issue, in case it is something specific about one of your answers that caused it to hang.

**Comment by TorontoFred** [comment]
Hello,  Erik,

Here is the URL to my Quora profile.   https://www.quora.com/profile/Fred-Paul-6

Thanks,
Fred

Sent from Mail for Windows 10

**Comment by eloquence** [comment]
Closing for now as another reporter confirms this fixed in the latest version.
