### ISSUE TITLE
Error with Quora plugin

### ISSUE THREAD

**Issue by theodox** [eloquence/freeyourstuff.cc#84]
```
Error: Attempt to obtain answer timed out after 30 seconds
    at extractAndStoreAnswer (file:///Users/stevet/Library/Application%20Support/Google/Chrome/Default/Extensions/hlkhpekhgcaigleojiocoeockhcaglia/0.3.24_0/src/plugins/quora/index.js:182:19)
```

**Comment by eloquence** [comment]
I was able to obtain your Quora answers, but I noticed that Quora itself experienced a few timeouts today, so it took a couple of tries. Regarding the overall time it takes to download, Quora will block the user's IP address for 24 hours if they attempt to download too quickly -- so the extension downloads the answers sequentially. 

I can send you your answers in JSON form if you email me at eloquence AT gmail DOT com. You can also try again, but I suggest waiting a few days, as I'm working on a few major updates that might improve the experienced.

**Comment by theodox** [comment]
I'll wait for the update and try it after that, thanks for looking into it.

**Comment by eloquence** [comment]
I've just released a major update to the extension (0.4.0) that should be a lot more tolerant of errors on the Quora side, and also faster with huge answer sets. Chrome auto-updates extensions, but to be sure, you can uninstall and reinstall the extension from https://freeyourstuff.cc/ - you can find the version you're running by putting chrome://extensions in the address bar.

There may be new errors, too! :-) Please give it a spin and let me know if it works for you now.

**Comment by theodox** [comment]
This worked.  I did see a lot of "something went wrong" popups as the answers were retrieved, is that on the Quora side or in the plugin?

**Comment by eloquence** [comment]
Yay! It's on Quora's side. Quora has been randomly throwing 504 errors the last few weeks. I don't think it's deliberate throttling, but it could be. The plugin should now just keep trying until it sees the data flow. ;-) (Quora also appears to sometimes miscount the answers, which is why you have a higher answer count in the dataset published on freeyourstuff.cc.)
